<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html class="cufon-active cufon-ready" xmlns="http://www.w3.org/1999/xhtml"><head>
<title><?php echo $sitename;?> | <?php echo site_url();?></title>

<link href="<?php echo base_url('src/front/'); ?>/index_files/main.css" rel="stylesheet" type="text/css">
 
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="keywords" content="chứng khoán,chung khoan,chứng khoán ảo Việt Nam,chung khoan ao Viet Nam,chứng khoán sms,mua bán chứng khoán ảo,mua ban chung khoan ao,chung khoan,chứng khoán,chung khoan ao,chứng khoán ảo,tro choi chung khoan,trò chơi chứng khoán,giao dich chung khoan,giao dịch chứng khoán,bang gia chung khoan,bảng giá chứng khoán,gia chung khoan,giá chứng khoán,ban gia truc tuyen,bảng giá trực tuyến,forex">
<meta name="description" content="<?php echo $description;?>">
<meta name="generator" content="0987016811">
 
 
<style type="text/css">cufon{text-indent:0!important;}@media screen,projection{cufon{display:inline!important;display:inline-block!important;position:relative!important;vertical-align:middle!important;font-size:1px!important;line-height:1px!important;}cufon cufontext{display:-moz-inline-box!important;display:inline-block!important;width:0!important;height:0!important;overflow:hidden!important;text-indent:-10000in!important;}cufon canvas{position:relative!important;}}@media print{cufon{padding:0!important;}cufon canvas{display:none!important;}}</style><script type="text/javascript" src="<?php echo base_url('src/front/'); ?>/index_files/UTMHelvetIns.js"></script><script type="text/javascript" src="<?php echo base_url('src/front/'); ?>/index_files/nganluong.js"></script><script type="text/javascript" src="<?php echo base_url('src/front/'); ?>/index_files/highslide.js"></script><script type="text/javascript" src="<?php echo base_url('src/front/'); ?>/index_files/config.js"></script><script type="text/javascript" src="<?php echo base_url('src/front/'); ?>/index_files/calendar.js"></script><script type="text/javascript" src="<?php echo base_url('src/front/'); ?>/index_files/en.js"></script><script type="text/javascript" src="<?php echo base_url('src/front/'); ?>/index_files/overlib.js"></script><script type="text/javascript" src="<?php echo base_url('src/front/'); ?>/index_files/timer.js"></script><script type="text/javascript" src="<?php echo base_url('src/front/'); ?>/index_files/prototype.js"></script><script type="text/javascript" src="<?php echo base_url('src/front/'); ?>/index_files/effects.js"></script><script type="text/javascript" src="<?php echo base_url('src/front/'); ?>/index_files/window.js"></script><script type="text/javascript" src="<?php echo base_url('src/front/'); ?>/index_files/autocomplete.js"></script><script type="text/javascript" src="<?php echo base_url('src/front/'); ?>/index_files/ajaxrequest.js"></script><script type="text/javascript" src="<?php echo base_url('src/front/'); ?>/index_files/ajaxfixer.js"></script><script type="text/javascript" src="<?php echo base_url('src/front/'); ?>/index_files/utility.js"></script><script type="text/javascript" src="<?php echo base_url('src/front/'); ?>/index_files/uploader.js"></script><script type="text/javascript" src="<?php echo base_url('src/front/'); ?>/index_files/sitemap.js"></script><script type="text/javascript" src="<?php echo base_url('src/front/'); ?>/index_files/sitemapconfig.js"></script><script type="text/javascript" src="<?php echo base_url('src/front/'); ?>/index_files/app.js"></script>
<style type="text/css">#PPDGFrame { z-index:20002; position:absolute; top:0; left:0; }#PPDGFrame .panel { z-index:20003; position:relative; }#PPDGFrame .panel iframe { width:516px; height:700px; border:0; }#PPDGFrame .panel .close { width:26px; height:26px; border:0; display:block; position:absolute; margin-left:486px; cursor:pointer; }#PPDGFrame .mask { z-index:20001; position:absolute; top:0; left:0; background-color:#000; opacity:0.6; filter:alpha(opacity=60); }</style><style type="text/css">.highslide img {cursor: url(/css/highslide/graphics/zoomin.cur), pointer !important;}.highslide-viewport-size {position: fixed; width: 100%; height: 100%; left: 0; top: 0}</style></head>
